# Generated by Django 5.0.6 on 2024-06-10 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FinanzasApp', '0001_initial'),
        ('InventarioApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('lugar', models.CharField(max_length=150)),
                ('numero_contacto', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('orden', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntradasApp.proveedor')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='PagoEntrada',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntradasApp.entrada')),
                ('metodo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanzasApp.metododepago')),
            ],
            options={
                'verbose_name': 'Pago Entrada',
                'verbose_name_plural': 'Pagos Entrada',
            },
        ),
        migrations.CreateModel(
            name='RelacionProductoEntrada',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntradasApp.entrada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventarioApp.producto')),
            ],
            options={
                'verbose_name': 'Relación Producto Entrada',
                'verbose_name_plural': 'Relaciones Producto Entrada',
            },
        ),
    ]
