# Generated by Django 5.0.6 on 2024-07-09 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntradasApp', '0001_initial'),
        ('FinanzasApp', '0001_initial'),
        ('GestionDeUsuariosApp', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoentrada',
            name='metodo_de_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanzasApp.metododepago'),
        ),
        migrations.AddField(
            model_name='pagoentrada',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntradasApp.proveedor'),
        ),
        migrations.AddField(
            model_name='relacionproductoentrada',
            name='entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntradasApp.entrada'),
        ),
    ]
