# Generated by Django 5.0.6 on 2024-07-10 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntradasApp', '0001_initial'),
        ('FinanzasApp', '0002_initial'),
        ('GestionDeUsuariosApp', '0001_initial'),
        ('InventarioApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagoentrada',
            name='entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntradasApp.entrada'),
        ),
        migrations.AddField(
            model_name='pagoentrada',
            name='metodo_de_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanzasApp.metododepago'),
        ),
        migrations.AddField(
            model_name='pagoentrada',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntradasApp.proveedor'),
        ),
        migrations.AddField(
            model_name='relacionproductoentrada',
            name='entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntradasApp.entrada'),
        ),
        migrations.AddField(
            model_name='relacionproductoentrada',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioApp.producto'),
        ),
        migrations.AddField(
            model_name='relacionproductoentrada',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant'),
        ),
    ]
