# Generated by Django 5.0.6 on 2024-07-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntradasApp', '0003_alter_entrada_tenant_alter_pagoentrada_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='cantidad_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
