# Generated by Django 5.0.6 on 2024-06-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntradasApp', '0003_entrada_tenant_pagoentrada_tenant_proveedor_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionproductoentrada',
            name='cantidad_devuelta',
            field=models.IntegerField(null=True),
        ),
    ]
