# Generated by Django 5.0.6 on 2024-07-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntradasApp', '0004_entrada_cantidad_total_alter_entrada_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='valor',
            new_name='valor_total',
        ),
    ]
