# Generated by Django 5.0.6 on 2024-07-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntradasApp', '0004_relacionproductoentrada_cantidad_devuelta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
