# Generated by Django 5.0.6 on 2024-07-26 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntradasApp', '0005_rename_valor_entrada_valor_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionproductoentrada',
            old_name='valor',
            new_name='valor_compra',
        ),
    ]
