# Generated by Django 5.0.6 on 2024-07-04 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntradasApp', '0005_alter_proveedor_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='usuario',
            new_name='user',
        ),
    ]
