# Generated by Django 5.0.6 on 2024-07-26 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntradasApp', '0006_rename_valor_relacionproductoentrada_valor_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionproductoentrada',
            old_name='valor_compra',
            new_name='valor',
        ),
    ]
