# Generated by Django 5.0.6 on 2024-07-05 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntradasApp', '0006_rename_usuario_entrada_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='user',
            new_name='usuario',
        ),
    ]
