# Generated by Django 5.0.6 on 2024-07-05 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntradasApp', '0007_rename_user_entrada_usuario'),
        ('FinanzasApp', '0008_remove_movimientos_user_movimientos_usuario_and_more'),
        ('InventarioApp', '0005_alter_producto_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntradasApp.proveedor'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagoentrada',
            name='entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntradasApp.entrada'),
        ),
        migrations.AlterField(
            model_name='pagoentrada',
            name='metodo_de_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanzasApp.metododepago'),
        ),
        migrations.AlterField(
            model_name='relacionproductoentrada',
            name='entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntradasApp.entrada'),
        ),
        migrations.AlterField(
            model_name='relacionproductoentrada',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioApp.producto'),
        ),
    ]
