# Generated by Django 5.0.6 on 2024-07-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntradasApp', '0007_rename_valor_compra_relacionproductoentrada_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionproductoentrada',
            name='valor_ultima_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
