# Generated by Django 5.0.6 on 2024-07-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntradasApp', '0008_relacionproductoentrada_valor_ultima_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
