# Generated by Django 5.0.6 on 2024-07-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntradasApp', '0010_entrada_valor_total_ajustado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='valor_total_ajustado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
