# Generated by Django 5.0.6 on 2024-07-29 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntradasApp', '0011_alter_entrada_valor_total_ajustado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['-id'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
    ]
