# Generated by Django 5.0.6 on 2024-06-10 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InventarioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=50)),
                ('referencia', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='MotivoDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Motivo de Devolución',
                'verbose_name_plural': 'Motivos de Devolución',
            },
        ),
        migrations.CreateModel(
            name='RelacionProductoDevolucion',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField()),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevolucionesApp.devolucion')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevolucionesApp.motivodevolucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventarioApp.producto')),
            ],
            options={
                'verbose_name': 'Relación Producto Devolución',
                'verbose_name_plural': 'Relaciones Producto Devolución',
            },
        ),
    ]
