# Generated by Django 5.0.6 on 2024-07-09 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionDeUsuariosApp', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('orden', models.CharField(blank=True, max_length=50)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=50)),
                ('referencia', models.CharField(max_length=50)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MotivoDevolucion',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant')),
            ],
            options={
                'verbose_name': 'Motivo de Devolución',
                'verbose_name_plural': 'Motivos de Devolución',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RelacionProductoDevolucion',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField()),
                ('valor_venta_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('devolucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DevolucionesApp.devolucion')),
                ('motivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DevolucionesApp.motivodevolucion')),
            ],
            options={
                'verbose_name': 'Relación Producto Devolución',
                'verbose_name_plural': 'Relaciones Producto Devolución',
                'ordering': ['id'],
            },
        ),
    ]
