# Generated by Django 5.0.6 on 2024-06-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevolucionesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucion',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='motivodevolucion',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='relacionproductodevolucion',
            name='tenant_id',
        ),
    ]
