# Generated by Django 5.0.6 on 2024-07-17 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevolucionesApp', '0002_initial'),
        ('GestionDeUsuariosApp', '0018_alter_usuarios_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant'),
        ),
        migrations.AlterField(
            model_name='motivodevolucion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant'),
        ),
        migrations.AlterField(
            model_name='relacionproductodevolucion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant'),
        ),
    ]
