# Generated by Django 5.0.6 on 2024-08-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevolucionesApp', '0003_alter_devolucion_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionproductodevolucion',
            name='ganancia_producto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
