# Generated by Django 5.0.6 on 2024-06-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevolucionesApp', '0004_rename_valor_devolucion_valor_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionproductodevolucion',
            old_name='valor',
            new_name='valor_venta_producto',
        ),
    ]
