# Generated by Django 5.0.6 on 2024-06-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevolucionesApp', '0005_rename_valor_relacionproductodevolucion_valor_venta_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucion',
            options={'ordering': ['id'], 'verbose_name': 'Devolución', 'verbose_name_plural': 'Devoluciones'},
        ),
        migrations.AlterModelOptions(
            name='motivodevolucion',
            options={'ordering': ['nombre'], 'verbose_name': 'Motivo de Devolución', 'verbose_name_plural': 'Motivos de Devolución'},
        ),
        migrations.AlterModelOptions(
            name='relacionproductodevolucion',
            options={'ordering': ['id'], 'verbose_name': 'Relación Producto Devolución', 'verbose_name_plural': 'Relaciones Producto Devolución'},
        ),
    ]
