# Generated by Django 5.0.6 on 2024-07-05 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevolucionesApp', '0006_alter_devolucion_options_and_more'),
        ('InventarioApp', '0005_alter_producto_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relacionproductodevolucion',
            name='devolucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DevolucionesApp.devolucion'),
        ),
        migrations.AlterField(
            model_name='relacionproductodevolucion',
            name='motivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DevolucionesApp.motivodevolucion'),
        ),
        migrations.AlterField(
            model_name='relacionproductodevolucion',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioApp.producto'),
        ),
    ]
