# Generated by Django 5.0.6 on 2024-07-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevolucionesApp', '0007_devolucion_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='orden',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
