# Generated by Django 5.0.6 on 2024-07-09 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionDeUsuariosApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('estilo', models.CharField(max_length=150)),
                ('talla', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=0)),
                ('stock_min', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['estilo', 'color', 'talla'],
            },
        ),
    ]
