# Generated by Django 5.0.6 on 2024-06-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('referencia', models.CharField(max_length=50)),
                ('estilo', models.CharField(max_length=150)),
                ('talla', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=0)),
                ('stock_min', models.IntegerField(default=0)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
