# Generated by Django 5.0.6 on 2024-06-10 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeUsuariosApp', '0002_tenant_alter_usuario_options_alter_usuario_groups_and_more'),
        ('InventarioApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='producto',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
