# Generated by Django 5.0.6 on 2024-06-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioApp', '0003_rename_disponibilidad_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
