# Generated by Django 5.0.6 on 2024-06-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeUsuariosApp', '0002_tenant_alter_usuario_options_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='state',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
