# Generated by Django 5.0.6 on 2024-07-05 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeUsuariosApp', '0003_tenant_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant'),
        ),
    ]
