# Generated by Django 5.0.6 on 2024-07-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeUsuariosApp', '0005_alter_usuarios_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='group',
        ),
    ]
