# Generated by Django 5.0.6 on 2024-07-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeUsuariosApp', '0009_remove_grupos_permisos_grupo_permisosgrupo_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_set', related_query_name='user', to='GestionDeUsuariosApp.grupos', verbose_name='groups'),
        ),
    ]
