# Generated by Django 5.0.6 on 2024-07-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeUsuariosApp', '0013_alter_usuarios_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_set', related_query_name='user', to='GestionDeUsuariosApp.grupos', verbose_name='groups'),
        ),
    ]
