# Generated by Django 5.0.6 on 2024-07-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeUsuariosApp', '0015_usuarios_grupos_alter_usuarios_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='grupos',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='groups',
            field=models.ManyToManyField(related_name='grupos_usuario', to='GestionDeUsuariosApp.permisosgrupo'),
        ),
    ]
