# Generated by Django 5.0.6 on 2024-07-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeUsuariosApp', '0016_remove_usuarios_grupos_alter_usuarios_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_set', to='GestionDeUsuariosApp.grupos'),
        ),
    ]
