# Generated by Django 5.0.6 on 2024-07-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeUsuariosApp', '0017_alter_usuarios_groups'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
            ],
        ),
    ]
