# Generated by Django 5.0.6 on 2024-07-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeUsuariosApp', '0018_alter_usuarios_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='grupo_permisos',
            field=models.ManyToManyField(blank=True, related_name='permisos_grupo', to='GestionDeUsuariosApp.permisosgrupo'),
        ),
    ]
