# Generated by Django 5.0.6 on 2024-08-09 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeUsuariosApp', '0020_remove_usuarios_username_alter_usuarios_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='es_socio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='porcentaje_participacion',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
