# Generated by Django 5.0.6 on 2024-06-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GastosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='tenant_id',
        ),
    ]
