# Generated by Django 5.0.6 on 2024-07-05 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanzasApp', '0008_remove_movimientos_user_movimientos_usuario_and_more'),
        ('GastosApp', '0002_alter_gasto_user_tipogasto_alter_gasto_tipo_gasto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='metodo_de_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanzasApp.metododepago'),
        ),
    ]
