# Generated by Django 5.0.6 on 2024-06-16 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GastosApp', '0003_gasto_tenant_alter_gasto_fecha_alter_gasto_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='metodo_pago',
            new_name='metodo_de_pago',
        ),
    ]
