# Generated by Django 5.0.6 on 2024-06-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GastosApp', '0004_rename_metodo_pago_gasto_metodo_de_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='usuario',
            new_name='user',
        ),
    ]
