# Generated by Django 5.0.6 on 2024-07-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GastosApp', '0004_tipogasto_predeterminado_entrada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-id'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
    ]
