# Generated by Django 5.0.6 on 2024-06-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GastosApp', '0005_rename_usuario_gasto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='orden',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
