# Generated by Django 5.0.6 on 2024-06-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GastosApp', '0006_alter_gasto_orden'),
    ]

    operations = [

        migrations.AlterField(
            model_name='gasto',
            name='orden',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
