# Generated by Django 5.0.6 on 2024-06-10 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FinanzasApp', '0001_initial'),
        ('InventarioApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('lugar', models.CharField(max_length=255)),
                ('numero_contacto', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('orden', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total_ajustado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancia_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancia_total_ajustada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_total', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasApp.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='RelacionProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('valor_venta_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_devuelta', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventarioApp.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasApp.venta')),
            ],
            options={
                'verbose_name': 'Relación Producto Venta',
                'verbose_name_plural': 'Relaciones Productos Ventas',
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanzasApp.metododepago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasApp.venta')),
            ],
            options={
                'verbose_name': 'Pago Venta',
                'verbose_name_plural': 'Pagos Ventas',
            },
        ),
    ]
