# Generated by Django 5.0.6 on 2024-07-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0002_alter_cliente_tenant_alter_pagoventa_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionproductoventa',
            name='cantidad_devuelta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
