# Generated by Django 5.0.6 on 2024-06-16 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0002_remove_cliente_tenant_id_remove_pagoventa_tenant_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagoventa',
            old_name='metodo_pago',
            new_name='metodo_de_pago',
        ),
    ]
