# Generated by Django 5.0.6 on 2024-06-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0003_rename_metodo_pago_pagoventa_metodo_de_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='pagoventa',
            options={'ordering': ['id'], 'verbose_name': 'Pago Venta', 'verbose_name_plural': 'Pagos Ventas'},
        ),
        migrations.AlterModelOptions(
            name='relacionproductoventa',
            options={'ordering': ['id'], 'verbose_name': 'Relación Producto Venta', 'verbose_name_plural': 'Relaciones Productos Ventas'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['orden'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
