# Generated by Django 5.0.6 on 2024-07-26 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0003_alter_relacionproductoventa_cantidad_devuelta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionproductoventa',
            old_name='valor_venta_producto',
            new_name='valor',
        ),
    ]
