# Generated by Django 5.0.6 on 2024-07-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0004_alter_cliente_options_alter_pagoventa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
