# Generated by Django 5.0.6 on 2024-07-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0004_rename_valor_venta_producto_relacionproductoventa_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionproductoventa',
            old_name='valor_compra',
            new_name='valor_ultima_compra',
        ),
    ]
