# Generated by Django 5.0.6 on 2024-07-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0005_rename_valor_compra_relacionproductoventa_valor_ultima_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
