# Generated by Django 5.0.6 on 2024-07-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0006_alter_cliente_estado_alter_venta_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-id'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_predeterminado',
            field=models.BooleanField(default=False),
        ),
    ]
