# Generated by Django 5.0.6 on 2024-08-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0007_alter_venta_options_cliente_cliente_predeterminado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
