# Generated by Django 5.0.6 on 2024-06-10 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cierre',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cierre',
                'verbose_name_plural': 'Cierres',
            },
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('metodo_de_pago', models.CharField(max_length=150)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision_banco', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('referencia', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_destino', to='FinanzasApp.metododepago')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_origen', to='FinanzasApp.metododepago')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
            },
        ),
    ]
