# Generated by Django 5.0.6 on 2024-07-09 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionDeUsuariosApp', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cierre',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant')),
            ],
            options={
                'verbose_name': 'Cierre',
                'verbose_name_plural': 'Cierres',
            },
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision_banco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('referencia', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_de_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanzasApp.metododepago')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('state', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('cuenta_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_destino', to='FinanzasApp.metododepago')),
                ('cuenta_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_origen', to='FinanzasApp.metododepago')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDeUsuariosApp.tenant')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['id'],
            },
        ),
    ]
