# Generated by Django 5.0.6 on 2024-06-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanzasApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierre',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='metododepago',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='tenant_id',
        ),
    ]
