# Generated by Django 5.0.6 on 2024-07-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanzasApp', '0003_alter_cierre_tenant_alter_metododepago_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metododepago',
            name='comision_banco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
