# Generated by Django 5.0.6 on 2024-06-12 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanzasApp', '0003_cierre_tenant_metododepago_tenant_movimientos_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='metodo_de_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanzasApp.metododepago'),
        ),
    ]
