# Generated by Django 5.0.6 on 2024-07-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanzasApp', '0004_alter_metododepago_comision_banco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientos',
            options={'ordering': ['-id'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='transferencia',
            options={'ordering': ['-id'], 'verbose_name': 'Transferencia', 'verbose_name_plural': 'Transferencias'},
        ),
    ]
