# Generated by Django 5.0.6 on 2024-06-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanzasApp', '0004_movimientos_metodo_de_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metododepago',
            old_name='metodo_de_pago',
            new_name='nombre',
        ),
    ]
