# Generated by Django 5.0.6 on 2024-06-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanzasApp', '0005_rename_metodo_de_pago_metododepago_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metododepago',
            options={'ordering': ['nombre'], 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='transferencia',
            options={'ordering': ['id'], 'verbose_name': 'Transferencia', 'verbose_name_plural': 'Transferencias'},
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
