# Generated by Django 5.0.6 on 2024-08-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanzasApp', '0006_remove_cierre_ganancia_remove_cierre_valor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierre',
            options={'ordering': ['-fecha'], 'verbose_name': 'Cierre', 'verbose_name_plural': 'Cierres'},
        ),
    ]
